version: '2'

services:
  db:
    image: 'postgres:13-alpine'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=file
    ports:
      - "5430:5432"
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - "9002:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: access_key
      MINIO_ROOT_PASSWORD: secret_key
  app:
    image: 'registry.hub.docker.com/2014003/file:1.0'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/file
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - BLOG_MINIO_ACCESS_KEY=access_key
      - BLOG_MINIO_SECRET_KEY=secret_key
      - BLOG_MINIO_URL=http://minio:9000
    ports:
      - "8080:8080"
    depends_on:
      - db

